package constant

const (
	ENV_DEBUG           = "DEBUG"
	ENV_PORT            = "PORT"
	ENV_GO_CLOCK_SERVER = "GO_CLOCK_SERVER"
	ENV_CONFIG_PATH     = "CONFIG_PATH"
	ENV_LOG_FILENAME    = "LOG_FILENAME"
	ENV_ENVIRONMENT     = "ENVIRONMENT"

	ENV_QUEUE_CONCURRENT_WORKERS = "QUEUE_CONCURRENT_WORKERS"
	ENV_QUEUE_CRITICAL_WORKERS   = "QUEUE_CRITICAL_WORKERS"
	ENV_QUEUE_DEFAULT_WORKERS    = "QUEUE_DEFAULT_WORKERS"
	ENV_QUEUE_LOW_WORKERS        = "QUEUE_LOW_WORKERS"
	ENV_QUEUE_REDIS_ADDRESS      = "QUEUE_REDIS_ADDRESS"

	ENV_RATE_LIMIT_REQ_PER_SEC   = "RATE_LIMIT_REQ_PER_SEC"
	ENV_RATE_LIMIT_BURST_REQUEST = "RATE_LIMIT_BURST_REQUEST"
	ENV_RATE_LIMIT_EXPIRES_IN    = "RATE_LIMIT_EXPIRES_IN"
)
